sudo: false
language:
  - python
services:
  - xvfb
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - pycodestyle mamba_utils
  - pytest --cov-config=.coveragerc --cov=mamba_utils --verbose --capture=no tests
  - pip install .
after_success:
  - codecov
notifications:
  email: false
cache:
  directories:
    - "$HOME/.cache/pip"

